version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/var/www/html:rw"
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 1s
      retries: 2
